name: ieee754

on:
  push:
    paths:
      - libs/ieee754/**
      - .github/workflows/ieee754.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/ieee754
