name: valarray

on:
  push:
    paths:
      - libs/valarray/**
      - .github/workflows/valarray.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/valarray
